config/routes.rb
Rails.application.routes.draw do
  devise_for :artists
  root "static_pages#home"

  get "about" => 'static_pages#about', as: :about
  get "contact" => 'static_pages#contact', as: :contact

  get "artists" => 'artists#index'
  get "artists/:id", to: 'artists#show'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 
  	def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_action :authenticate_artist!, only: :show

	def home
	end

  	def index
    	@artists = Artist.all
  	end

  	def new
  		@artist = Artist.new
  	end

	def show
		@artist = Artist.find(params[:id])
		render 'artists/show'
	end

  	def create
    	@artist = Artist.new(artist_params)
    		if artist.save
      			redirect_to '/'
    		else
      	redirect_to '/artists/sign_up'
      	end
    end

    def edit
		@artist = Artist.find(params[:id])
	end

	def destroy
    	@artist = Artist.find(params[:id])
    	@artist.destroy
    	redirect_to artists_path
	end
     

  private

  def artist_params
    params.require(:artist).permit(
      :email,
      :password, :password_confirmation
    )
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/artists/index.html.erb
<h1>Our amazing artists</h1>
<ul>
  <% @artists.each do |artist| %>
  <li>Name: <%= artist.name %> | Email: <%= artist.email %></li>
  <% end %>
</ul>

app/views/artists/show.html.erb
<% if artist_signed_in? %>
	<h2>Welcome <%= current_artist.name %>!</h2>

	<%= link_to 'Logout', destroy_artist_session_path, method: 'DELETE' %>

	<% else %>

	<h2> Nobody logged in</h2>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'shared/navbar' %> 
  <div class="main-page-content <%= controller.controller_name %>">
    <%= yield %>
  </div>

  <%= render 'shared/footer' %> 

  </body>
</html>

app/views/shared/_footer.html.erb
<div class="container">
	<p class="lead">need to add footer</p>
	<p><%= link_to 'Home', root_path %> | <%= link_to 'About', about_path %> | <%= link_to 'Contact', contact_path %></p>
	<p>then add style elements</p>
	<p>then clean up style elements</p>
	<p><small>this is just an example of small text</small></p>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Artbnb", root_path %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Register Your Venue" %></li>
        <li><%= link_to "Upload Your Art" %></li>
        <li><%= link_to "Browse Venues" %></li>
        <li><%= link_to "View Artists", artists_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Artists <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Register", new_artist_registration_path %></li>
            <li><%= link_to "Sign In", new_artist_session_path %></li>
            <li><%= link_to "Log Out", destroy_artist_session_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Patrons <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Register" %></li>
            <li><%= link_to "Sign In" %></li>
            <li><%= link_to "Log Out" %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav> 

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="container-fluid">
  <div class="jumbotron bg-hero-banner white-header-text" align="center">
    <h1>Make Art,<br>Get Money!</h1>
    <p>Artbnb connects ARTISTS with motherfuckers who need art.</p>
    <br><br>
     <div class="row" align="center">
        <div class="col-lg-2 col-xs-2"> </div>
        <div class="col-lg-8 col-xs-8"><button type="button" class="btn btn-info btn-lg purple-button">Register for Artbnb</button></div>
        <div class="col-lg-2 col-xs-2"> </div>
     </div>
  </div>
  <div class="row" align="center">
    <div class="col-lg-2 col-xs-2"> </div>
    <div class="col-lg-8 col-xs-8"><h2>How Artbnb Works</h2></div>
    <div class="col-lg-2 col-xs-2"> </div>
  </div>
  <div class="row" align="center">
    <div class="col-lg-2 col-xs-2"> </div>
    <div class="col-lg-4 col-xs-4"><h4>If You Are An Artist</h4></div>
    <div class="col-lg-4 col-xs-4"><h4>If You Are In Need Of Art</h4></div>
    <div class="col-lg-2 col-xs-2"> </div>
  </div>
  <div class="row" align="center">
    <div class="col-lg-4 col-md-4 col-xs-12 bg-danger">add icon <br>Register as an Artist<br>add description</div>
    <div class="col-lg-4 col-md-4 col-xs-12 bg-warning">add icon <br>Upload your Artwork<br>add description</div>
    <div class="col-lg-4 col-md-4 col-xs-12 bg-success">add icon <br>Connect with Buyers<br>add description</div>
  </div> 
  <div class="row bg-venues-banner" align="center">
    <div class="col-lg-4 col-md-4 col-xs-12">
      <div class="thumbnail">
        <div class="caption">
          <h3>Beaker & Gray</h3>
          <p>Global-inspired fare & inventive cocktails served in a former factory space with rustic accents.<br><a href="tel:305-699-2637">(305) 699-2637</a><br>2637 N Miami Ave, Miami, FL 33127</p>
          <p><a href="#" class="btn btn-primary" role="button">Find Out More</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-xs-12">
      <div class="thumbnail">
        <div class="caption">
          <h3>BUILDING Miami</h3>
          <p>BUILDING is the premier shared workspace for growing tech companies and startups in Miami.<br><a href="tel:305-372-0075">(305) 372-0075</a><br>120 SW 8th St, Miami, FL 33130</p>
          <p><a href="#" class="btn btn-primary" role="button">Find Out More</a></p>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-xs-12">
      <div class="thumbnail">
        <div class="caption">
          <h3>Pacific54</h3>
          <p>Pacific54 is an experienced, diverse Miami SEO Company with a passion for internet marketing.<br><a href="tel:305-515-5473">(305) 515-5473</a><br>2750 NW 3rd Ave #17, Miami, FL 33127</p>
          <p><a href="#" class="btn btn-primary" role="button">Find Out More</a></p>
        </div>
      </div>
    </div>
    <button type="button" class="btn btn-info purple-button btn-lg">See more Venues!</button>
    <button type="button" class="btn btn-info purple-button btn-lg">Register your Venue!</button>
  </div>
  <div class="jumbotron bg-homepage-info" align="center">
    <div class="row" align="center">
        <div class="col-lg-2 col-xs-2"> </div>
        <div class="col-lg-8 col-xs-8"><h6>When you sign up as an artist with Artbnb, you will have access to a vast network of people looking to either buy or rent your artwork. Additionally, interested people can also reach out to commission you for specific work.</h6><br></div>
        <div class="col-lg-2 col-xs-2"> </div>
    </div>
    <div class="row" align="center">
        <div class="col-lg-2 col-xs-2"> </div>
        <div class="col-lg-8 col-xs-8"><button type="button" class="btn btn-info btn-lg purple-button">Register as an artist with Artbnb</button></div>
        <div class="col-lg-2 col-xs-2"> </div>
    </div>  
    <br>
    <div class="row" align="center">
        <div class="col-lg-2 col-xs-2"> </div>
        <div class="col-lg-8 col-xs-8"><h6>Conversely, when you sign up as a patron with Artbnb, you will have access to a wide range of artists who either have art they have already produced and are looking to rent or sell, or they are available to produce custom art pieces. Additionally, any business or property owners can register their venue on Artbnb to be contacted by artists who are interested in displaying their work for a small daily or weekly fee, but with no commission fees if their art is sold on-site.</h6><br></div>
        <div class="col-lg-2 col-xs-2"> </div>
    </div>
    <div class="row" align="center">
        <div class="col-lg-2 col-xs-2"> </div>
        <div class="col-lg-8 col-xs-8"><button type="button" class="btn btn-info btn-lg purple-button">Register as a patron with Artbnb</button></div>
        <div class="col-lg-2 col-xs-2"> </div>
    </div>  
  </div>
</div>